version: 1.2.1-{build}
image:
- Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
after_build:
- cmd: >-
    mkdir artefacts
    
    nuget pack RCT2ObjectData\RCT2ObjectData.csproj -OutputDirectory artefacts -Properties Configuration=Release
artifacts:
- path: 'artefacts\**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: iSwkaG9yWD6WUaWH3JwB3o7go4cc08IaJkklxSnuIoDY0i6/zQEOG8/kPCAOEN4a
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
